[36m[backend][0m [32minfo[39m: [Middleware] Using AdminSystem gateway for authentication
[36m[backend][0m [32minfo[39m: [35m[TokenManager][0m Initialized new TokenManager instance for model: gpt-3.5-turbo
[36m[backend][0m [32minfo[39m: [35m[TokenManager][0m Returning existing instance for model: gpt-3.5-turbo
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (node:net:1940:16)
    at listenInCluster (node:net:1997:12)
    at Server.listen (node:net:2102:7)
    at Function.serverListen [as listen] (/Users/linhpham/Desktop/test/Genomain/server/node_modules/@mintplex-labs/express-ws/dist/index.js:91:21)
    at bootHTTP (/Users/linhpham/Desktop/test/Genomain/server/utils/boot/index.js:58:6)
    at Object.<anonymous> (/Users/linhpham/Desktop/test/Genomain/server/index.js:140:32)
    at Module._compile (node:internal/modules/cjs/loader:1730:14)
    at Object..js (node:internal/modules/cjs/loader:1895:10)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (node:events:530:35)
    at emitErrorNT (node:net:1976:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 3001
}

Node.js v22.17.1
